[package]
name = "ono"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
onoi = { path = "../onoi" }
clap = { version = "4.1.8", features = ["derive"] }
